// Generated by gencpp from file control_can_motor/Motor.msg
// DO NOT EDIT!


#ifndef CONTROL_CAN_MOTOR_MESSAGE_MOTOR_H
#define CONTROL_CAN_MOTOR_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_can_motor
{
template <class ContainerAllocator>
struct Motor_
{
  typedef Motor_<ContainerAllocator> Type;

  Motor_()
    : motor_id(0)
    , current(0)
    , velocity(0)
    , position(0)  {
    }
  Motor_(const ContainerAllocator& _alloc)
    : motor_id(0)
    , current(0)
    , velocity(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef uint8_t _motor_id_type;
  _motor_id_type motor_id;

   typedef int16_t _current_type;
  _current_type current;

   typedef int16_t _velocity_type;
  _velocity_type velocity;

   typedef int16_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::control_can_motor::Motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_can_motor::Motor_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_

typedef ::control_can_motor::Motor_<std::allocator<void> > Motor;

typedef boost::shared_ptr< ::control_can_motor::Motor > MotorPtr;
typedef boost::shared_ptr< ::control_can_motor::Motor const> MotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_can_motor::Motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_can_motor::Motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_can_motor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'control_can_motor': ['/home/pi/code/loui_robot_rasp4b_test/ros_ws/src/control_can_motor/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_can_motor::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_can_motor::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_can_motor::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_can_motor::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_can_motor::Motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_can_motor::Motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_can_motor::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37986fc1a8f0287c7889edd26eaf11a1";
  }

  static const char* value(const ::control_can_motor::Motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37986fc1a8f0287cULL;
  static const uint64_t static_value2 = 0x7889edd26eaf11a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_can_motor::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_can_motor/Motor";
  }

  static const char* value(const ::control_can_motor::Motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_can_motor::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 motor_id\n\
int16 current\n\
int16 velocity\n\
int16 position\n\
";
  }

  static const char* value(const ::control_can_motor::Motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_can_motor::Motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_id);
      stream.next(m.current);
      stream.next(m.velocity);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_can_motor::Motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_can_motor::Motor_<ContainerAllocator>& v)
  {
    s << indent << "motor_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_id);
    s << indent << "current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.current);
    s << indent << "velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.velocity);
    s << indent << "position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CAN_MOTOR_MESSAGE_MOTOR_H
